#!/usr/bin/env bash
# khulnasoft-installer - shell script to install khulnasoft
# https://github.com/khulnasoftproj/khulnasoft-installer

set -eu

usage_exit() {
  echo "Usage: $0 [-v version]" 1>&2
  exit 1
}

uname_os() {
  local os
  os=$(uname -s | tr '[:upper:]' '[:lower:]')
  case "$os" in
    cygwin_nt*) os="windows" ;;
    mingw*) os="windows" ;;
    msys_nt*) os="windows" ;;
  esac
  echo "$os"
}

uname_arch() {
  local arch
  arch=$(uname -m)
  case $arch in
    x86_64) arch="amd64" ;;
    aarch64) arch="arm64" ;;
  esac
  echo ${arch}
}

OS="$(uname_os)"
ARCH="$(uname_arch)"

install_path=${KHULNASOFT_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/khulnasoftproj-khulnasoft}/bin/khulnasoft
if [ "$OS" = windows ]; then
  install_path=${KHULNASOFT_ROOT_DIR:-$HOME/AppData/Local/khulnasoftproj-khulnasoft}/bin/khulnasoft.exe
fi

while getopts v: OPT
do
  case $OPT in
    v) version=$OPTARG
      ;;
    \?) usage_exit
      ;;
  esac
done

shift $((OPTIND - 1))

bootstrap_version=v2.9.0

filename=khulnasoft_${OS}_${ARCH}.tar.gz
URL=https://github.com/khulnasoftproj/khulnasoft/releases/download/$bootstrap_version/$filename

tempdir=$(mktemp -d)
echo "===> Installing khulnasoft $bootstrap_version for bootstrapping..." >&2
echo "===> Downloading $URL ..." >&2
curl --fail -L "$URL" -o "$tempdir/$filename"

cd "$tempdir"

echo "===> Verifying checksum of khulnasoft $bootstrap_version ..." >&2
if command -v sha256sum > /dev/null 2>&1; then
  echo "$checksums" | grep "$filename" | sha256sum -c
elif command -v shasum > /dev/null 2>&1; then
  echo "$checksums" | grep "$filename" | shasum -a 256 -c
else
	echo "Skipped checksum verification of khulnasoft $bootstrap_version, because both sha256sum and shasum aren't found" >&2
fi

tar xvzf "$filename" > /dev/null
chmod a+x khulnasoft
if [ -n "${version:-}" ]; then
	echo "===> $tempdir/khulnasoft update-khulnasoft $version" >&2
	./khulnasoft update-khulnasoft "$version"
else
	echo "===> $tempdir/khulnasoft update-khulnasoft" >&2
	./khulnasoft update-khulnasoft
fi

"$install_path" -v

rm -R "$tempdir"
