---
name: test-actions-windows
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
jobs:
  test-actions-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          khulnasoft_version: v1.18.0
          working_directory: tests
      - run: command -v khulnasoft
      - run: khulnasoft -v
      - run: github-comment -v
        working-directory: tests
  test-actions-windows-absolute-path:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          khulnasoft_version: v1.18.0
          install_path: /tmp/bin/khulnasoft.exe
          working_directory: tests
      - run: /tmp/bin/khulnasoft -v
  test-actions-windows-relative-path:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          khulnasoft_version: v1.18.0
          install_path: bin/khulnasoft.exe
          working_directory: tests
      - run: tests/bin/khulnasoft -v
