
---
name: test-actions-windows-pwsh
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
jobs:
  normal:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          khulnasoft_version: v2.9.0
      - run: command -v khulnasoft
        shell: pwsh
      - run: khulnasoft -v
        shell: pwsh
      - run: actionlint -version
        shell: pwsh
        working-directory: tests
  working_dir:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          khulnasoft_version: v2.9.0
          working_directory: tests
      - run: command -v khulnasoft
        shell: pwsh
      - run: khulnasoft -v
        shell: pwsh
      - run: github-comment -v
        shell: pwsh
        working-directory: tests
